# Generated by Django 5.0.1 on 2026-01-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_smart_matching'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='match',
            name='accounts_ma_user_a__idx',
        ),
        migrations.RemoveIndex(
            model_name='match',
            name='accounts_ma_user_b__idx',
        ),
        migrations.RemoveIndex(
            model_name='matchhistory',
            name='accounts_ma_user_id_idx',
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['user_a', 'status', '-compatibility_score'], name='accounts_ma_user_a__745f96_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['user_b', 'status', '-compatibility_score'], name='accounts_ma_user_b__dc0e4e_idx'),
        ),
        migrations.AddIndex(
            model_name='matchhistory',
            index=models.Index(fields=['user', 'action', '-created_at'], name='accounts_ma_user_id_331147_idx'),
        ),
    ]
