# Generated by Django 5.0.1 on 2026-01-27 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_credit_system_enhancement'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='skillcredit',
            new_name='accounts_sk_to_user_5f2d3b_idx',
            old_name='accounts_sk_to_user_idx',
        ),
        migrations.RenameIndex(
            model_name='skillcredit',
            new_name='accounts_sk_transac_a74d89_idx',
            old_name='accounts_sk_transac_idx',
        ),
        migrations.RenameIndex(
            model_name='skillswapjob',
            new_name='accounts_sk_request_4ab6bd_idx',
            old_name='accounts_sk_require_idx',
        ),
        migrations.RenameIndex(
            model_name='skillswapjob',
            new_name='accounts_sk_provide_d205e4_idx',
            old_name='accounts_sk_provide_idx',
        ),
        migrations.AlterField(
            model_name='skillcredit',
            name='description',
            field=models.TextField(help_text='Description of the transaction'),
        ),
        migrations.AlterField(
            model_name='skillcredit',
            name='to_user',
            field=models.ForeignKey(help_text='User receiving/earning credits', on_delete=django.db.models.deletion.CASCADE, related_name='credits_received', to=settings.AUTH_USER_MODEL),
        ),
    ]
