# Generated by Django 5.0.1 on 2025-12-12 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_favoriteprovider'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Describe your project in detail')),
                ('timeline', models.CharField(choices=[('asap', 'As soon as possible'), ('this_week', 'This week'), ('next_week', 'Next week'), ('this_month', 'This month'), ('flexible', 'Flexible')], default='flexible', max_length=20)),
                ('budget', models.CharField(choices=[('under_100', 'Under $100'), ('100_500', '$100 - $500'), ('500_1000', '$500 - $1,000'), ('1000_5000', '$1,000 - $5,000'), ('5000_plus', '$5,000+'), ('not_sure', 'Not sure yet')], default='not_sure', max_length=20)),
                ('preferred_contact', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('either', 'Either')], default='either', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('service_address', models.CharField(blank=True, max_length=255)),
                ('service_city', models.CharField(blank=True, max_length=100)),
                ('service_zip', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('viewed', 'Viewed'), ('quoted', 'Quote Sent'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('quote_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quote_message', models.TextField(blank=True)),
                ('quoted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_requests', to='providers.serviceprovider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quote Request',
                'verbose_name_plural': 'Quote Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
