# Generated by Django 5.0.1 on 2025-12-12 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0003_quoterequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='providers/gallery/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('alt_text', models.CharField(blank=True, help_text='Description for accessibility', max_length=255)),
                ('is_featured', models.BooleanField(default=False, help_text='Featured images appear first')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='providers.serviceprovider')),
            ],
            options={
                'verbose_name': 'Provider Image',
                'verbose_name_plural': 'Provider Images',
                'ordering': ['-is_featured', 'order', '-created_at'],
            },
        ),
    ]
