# Generated by Django 5.0.1 on 2025-12-12 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0004_providerimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='is_emergency',
            field=models.BooleanField(default=False, help_text='Emergency/urgent request'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='accepts_emergency',
            field=models.BooleanField(default=False, help_text='Accepts emergency/urgent requests'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='emergency_rate_info',
            field=models.CharField(blank=True, help_text='Info about emergency rates (e.g., "25% premium for emergencies")', max_length=100),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='is_available_now',
            field=models.BooleanField(default=False, help_text='Currently available for jobs'),
        ),
    ]
