# Generated by Django 5.0.1 on 2026-01-27 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0007_unified_job_system'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='jobmessage',
            new_name='providers_j_job_id_1dba54_idx',
            old_name='providers_jo_job_id_2_idx',
        ),
        migrations.RenameIndex(
            model_name='jobmessage',
            new_name='providers_j_recipie_7035c7_idx',
            old_name='providers_jo_recipie_idx',
        ),
        migrations.RenameIndex(
            model_name='jobproposal',
            new_name='providers_j_job_id_70775d_idx',
            old_name='providers_jo_job_id_idx',
        ),
        migrations.RenameIndex(
            model_name='jobproposal',
            new_name='providers_j_propose_8c2742_idx',
            old_name='providers_jo_propose_idx',
        ),
        migrations.RenameIndex(
            model_name='unifiedjob',
            new_name='providers_u_request_9da9d2_idx',
            old_name='providers_un_require_idx',
        ),
        migrations.RenameIndex(
            model_name='unifiedjob',
            new_name='providers_u_provide_be5ead_idx',
            old_name='providers_un_provide_idx',
        ),
        migrations.RenameIndex(
            model_name='unifiedjob',
            new_name='providers_u_payment_d2f99f_idx',
            old_name='providers_un_payment_idx',
        ),
    ]
