# Generated by Django 5.0.1 on 2026-01-27 17:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_accounts_sk_to_user_idx_accounts_sk_to_user_5f2d3b_idx_and_more'),
        ('providers', '0010_community_projects'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='projectapplication',
            name='unique_role_application',
        ),
        migrations.RemoveConstraint(
            model_name='projectmember',
            name='unique_project_member',
        ),
        migrations.RemoveConstraint(
            model_name='skilldemand',
            name='unique_skill_demand_period',
        ),
        migrations.RemoveConstraint(
            model_name='skillmarketopportunity',
            name='unique_skill_opportunity_period',
        ),
        migrations.RemoveConstraint(
            model_name='skillsupply',
            name='unique_skill_supply_period',
        ),
        migrations.RemoveConstraint(
            model_name='userbadgeaward',
            name='unique_user_badge',
        ),
        migrations.RenameIndex(
            model_name='communityproject',
            new_name='providers_c_status_42ae57_idx',
            old_name='providers_co_status_idx',
        ),
        migrations.RenameIndex(
            model_name='communityproject',
            new_name='providers_c_project_e9335e_idx',
            old_name='providers_co_project_idx',
        ),
        migrations.RenameIndex(
            model_name='communityproject',
            new_name='providers_c_locatio_575898_idx',
            old_name='providers_co_locatio_idx',
        ),
        migrations.RenameIndex(
            model_name='communityproject',
            new_name='providers_c_is_feat_d636c4_idx',
            old_name='providers_co_is_feat_idx',
        ),
        migrations.RenameIndex(
            model_name='projectapplication',
            new_name='providers_p_role_id_caf455_idx',
            old_name='providers_pr_role_id_idx',
        ),
        migrations.RenameIndex(
            model_name='projectapplication',
            new_name='providers_p_applica_7b9a06_idx',
            old_name='providers_pr_applica_idx',
        ),
        migrations.RenameIndex(
            model_name='projectmember',
            new_name='providers_p_project_5cc3a6_idx',
            old_name='providers_pr_project_idx',
        ),
        migrations.RenameIndex(
            model_name='projectmember',
            new_name='providers_p_user_id_c3aafa_idx',
            old_name='providers_pr_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='projectmessage',
            new_name='providers_p_project_c6d7e1_idx',
            old_name='providers_pr_project_2_idx',
        ),
        migrations.RenameIndex(
            model_name='skilldemand',
            new_name='providers_s_city_161dbc_idx',
            old_name='providers_sk_city_st_idx',
        ),
        migrations.RenameIndex(
            model_name='skilldemand',
            new_name='providers_s_skill_i_f2fcf8_idx',
            old_name='providers_sk_skill_c_idx',
        ),
        migrations.RenameIndex(
            model_name='skilldemand',
            new_name='providers_s_demand__738c67_idx',
            old_name='providers_sk_demand__idx',
        ),
        migrations.RenameIndex(
            model_name='skillmarketopportunity',
            new_name='providers_s_city_839188_idx',
            old_name='providers_sk_city_st_3_idx',
        ),
        migrations.RenameIndex(
            model_name='skillmarketopportunity',
            new_name='providers_s_market__0fae61_idx',
            old_name='providers_sk_market__idx',
        ),
        migrations.RenameIndex(
            model_name='skillmarketopportunity',
            new_name='providers_s_skill_i_327561_idx',
            old_name='providers_sk_skill_c_3_idx',
        ),
        migrations.RenameIndex(
            model_name='skillsupply',
            new_name='providers_s_city_522c0c_idx',
            old_name='providers_sk_city_st_2_idx',
        ),
        migrations.RenameIndex(
            model_name='skillsupply',
            new_name='providers_s_skill_i_74e999_idx',
            old_name='providers_sk_skill_c_2_idx',
        ),
        migrations.RenameIndex(
            model_name='skillsupply',
            new_name='providers_s_supply__654f3d_idx',
            old_name='providers_sk_supply_idx',
        ),
        migrations.RenameIndex(
            model_name='userbadgeaward',
            new_name='providers_u_user_id_dd8f31_idx',
            old_name='providers_us_user_id_idx',
        ),
        migrations.AlterField(
            model_name='projectmilestone',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, help_text='Team members assigned to this milestone', related_name='assigned_milestones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectrole',
            name='skills_preferred',
            field=models.ManyToManyField(blank=True, help_text='Additional preferred skills', related_name='preferred_roles', to='accounts.skill'),
        ),
        migrations.AlterUniqueTogether(
            name='projectapplication',
            unique_together={('role', 'applicant')},
        ),
        migrations.AlterUniqueTogether(
            name='projectmember',
            unique_together={('project', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='skilldemand',
            unique_together={('skill', 'city', 'state', 'zip_code', 'period_start', 'period_end')},
        ),
        migrations.AlterUniqueTogether(
            name='skillmarketopportunity',
            unique_together={('skill', 'city', 'state', 'zip_code', 'period_start', 'period_end')},
        ),
        migrations.AlterUniqueTogether(
            name='skillsupply',
            unique_together={('skill', 'city', 'state', 'zip_code', 'period_start', 'period_end')},
        ),
        migrations.AlterUniqueTogether(
            name='userbadgeaward',
            unique_together={('user', 'badge')},
        ),
    ]
